#  **Predicting Investment Portfolio Performance Using Portfolio using Artificial Neural Networks (ANN)**

# Project Type
# Deep Learning

## **Business Background**

**FinGrow Wealth Advisors** is a financial advisory company that manages investment portfolios for thousands of clients across India. Every year, the company reviews each client's investment performance and uses historical data to improve future investment decisions.

The company has collected data from **5,000 investors**. For each investor, information such as age, annual income, investment amount, risk appetite, investment experience, market exposure, portfolio diversification, and previous year's return has been recorded.

The management wants to use Artificial Intelligence (AI) to analyze this data and answer different business questions. Interestingly, the **same dataset** can be used for three different machine learning problems simply by changing the target variable.

---

## Dataset Description

The dataset contains the following variables:

| Variable            | Description                                        |
| ------------------- | -------------------------------------------------- |
| Age                 | Age of the investor (years)                        |
| Income (Lakh ₹)     | Annual income of the investor                      |
| Investment (Lakh ₹) | Total investment amount                            |
| Risk Score          | Risk appetite of the investor (1–10)               |
| Experience          | Investment experience (years)                      |
| Market Exposure (%) | Percentage of investment in equity markets         |
| Diversification     | Number of different asset classes in the portfolio |
| Previous Return (%) | Annual return achieved in the previous year        |

The company has also calculated the actual **Annual Return (%)** earned by each investor.

---

## **Learning Outcome**

This case  demonstrates an important concept in Machine Learning:

* The **input features (X) remain exactly the same**.
* Only the **target variable (y)** changes according to the business requirement.

| Business Requirement                             | Target Variable   | Machine Learning Problem   |
| ------------------------------------------------ | ----------------- | -------------------------- |
| Predict the exact annual return                  | Annual Return (%) | Regression                 |
| Predict whether return is High or Low            | Return Binary     | Binary Classification      |
| Predict whether return is Low, Moderate, or High | Return Category   | Multi-class Classification |

This illustrates that the **type of machine learning problem is determined by the business objective and the target variable—not by the input data.**

## **Business Scenario 1: Regression**
**Business Question**

What annual return (%) is expected for a new investor?

The company wants to estimate the exact annual return that an investor is likely to earn based on the available information.

**Target Variable**

Annual Return (%)

Example

Investor	Predicted Annual Return (%)

a.	18.4

b.	11.7

c.	22.3

Since the target is a continuous numerical value, this is a Regression problem.

## **Business Scenario 2: Binary Classification**

**Business Question**
Instead of predicting the exact return, management now wants a simpler decision.

Will the investor earn a High Return (15% or more) or not?

The annual return is converted into two categories:

- 0 = Low Return (less than 15%)
- 1 = High Return (15% or more)

**Target Variable**

Return Binary

Example

Annual Return (%)	Return Binary
- 18.4	1
- 11.7	0
- 22.3	1

Since there are only two possible classes, this becomes a Binary Classification problem.

## **Business Scenario 3: Multi-class Classification**
**Business Question**

The company now wants to classify investors into three performance categories for portfolio management.

The annual return is divided into:

1. Low Return : Less than 10%
2. Moderate Return : 10% to 20%
3. High Return : More than 20%


These categories are encoded as:

- 0 = Low
- 1 = Moderate
- 2 = High

**Target Variable**

Return Category

Example

Annual Return (%)	Category
- 8.6	Low
- 16.8	Moderate
- 23.5	High

Since there are three classes, this becomes a Multi-class Classification problem.

**Data Set:** https://github.com/YBIFoundation/DeepLearning/raw/main/PredictingInvestmentPortfolioPerformance.csv

## **Solution**

In [1]:
# Step 1: Import Library
import pandas as pd
import numpy as np

In [2]:
# Step 2: Read dataset
df = pd.read_csv('https://github.com/YBIFoundation/DeepLearning/raw/main/PredictingInvestmentPortfolioPerformance.csv')

In [3]:
df.head()

,age,income_lakh,investment_lakh,risk_score,experience,market_exposure,diversification,previous_return,annual_return,return_binary,return_category
0,53,18.2,5.1,10,2,15.4,9,2.0,21.7,1,2
1,36,23.5,12.6,7,14,89.5,3,2.0,27.9,1,2
2,57,6.7,5.1,1,12,95.1,1,6.0,6.0,0,0
3,29,4.4,5.6,1,13,65.4,9,18.9,13.5,0,1
4,45,21.9,11.2,1,5,24.2,6,15.3,18.2,1,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              5000 non-null   int64
 1   income_lakh      5000 non-null   float64
 2   investment_lakh  5000 non-null   float64
 3   risk_score       5000 non-null   int64
 4   experience       5000 non-null   int64
 5   market_exposure  5000 non-null   float64
 6   diversification  5000 non-null   int64
 7   previous_return  5000 non-null   float64
 8   annual_return    5000 non-null   float64
 9   return_binary    5000 non-null   int64
 10  return_category  5000 non-null   int64
dtypes: float64(5), int64(6)
memory usage: 429.8 KB

In [5]:
df.describe()

,age,income_lakh,investment_lakh,risk_score,experience,market_exposure,diversification,previous_return,annual_return,return_binary,return_category
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000
mean,40.524000,13.925780,7.783780,5.491600,14.828400,55.084080,5.453000,9.70880,17.992440,0.682000,1.272000
std,11.495767,6.363301,4.171184,2.880067,8.876301,26.119183,2.871696,8.65714,6.350595,0.465746,0.636944
min,21.000000,3.000000,0.500000,1.000000,0.000000,10.000000,1.000000,-5.00000,-2.000000,0.000000,0.000000
25%,31.000000,8.400000,4.200000,3.000000,7.000000,32.100000,3.000000,2.20000,13.600000,0.000000,1.000000
50%,40.000000,14.000000,7.800000,6.000000,15.000000,55.100000,5.000000,9.60000,18.000000,1.000000,1.000000
75%,51.000000,19.500000,11.400000,8.000000,23.000000,78.000000,8.000000,17.10000,22.300000,1.000000,2.000000
max,60.000000,25.000000,15.000000,10.000000,30.000000,100.000000,10.000000,25.00000,39.800000,1.000000,2.000000

In [6]:
# Step 3: Define y and X

In [7]:
df.columns

Index(['age', 'income_lakh', 'investment_lakh', 'risk_score', 'experience',
       'market_exposure', 'diversification', 'previous_return',
       'annual_return', 'return_binary', 'return_category'],
      dtype='object')

In [8]:
X = df[['age', 'income_lakh', 'investment_lakh', 'risk_score', 'experience',  'market_exposure', 'diversification', 'previous_return']]

In [9]:
y_r = df['annual_return'] # no preprocessing

In [10]:
y_b = df['return_binary'] # no preprocessing

In [11]:
y_m = df['return_category'] # preprocessing OneHotEncoding / to_categorical

In [12]:
from keras.utils import to_categorical

ModuleNotFoundError: No module named 'keras'

In [ ]:
y_m = to_categorical(y_m)

In [ ]:
# Step 4: Train test split
from sklearn.model_selection import train_test_split

# **Regression**

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y_r,random_state=2529)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()

In [ ]:
X_train = mms.fit_transform(X_train)

In [ ]:
X_test = mms.transform(X_test)

In [ ]:
# Step 5: Build ANN model
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(8, activation='relu'))

In [ ]:
model.add(Dense(16, activation='relu'))

In [ ]:
model.add(Dense(1, activation='linear'))

In [ ]:
model.compile(optimizer='adam',loss='mean_squared_error')

In [ ]:
# Step 6: Train model
model.fit(X_train,y_train,epochs=10,batch_size=32)

In [ ]:
model.summary()

In [ ]:
# Step 7: Prediction
y_pred = model.predict(X_test)

In [ ]:
# Step 8: Evaluate
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pred)

# **Binary Classification**

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y_b,random_state=2529)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()

In [ ]:
X_train = mms.fit_transform(X_train)

In [ ]:
X_test = mms.transform(X_test)

In [ ]:
# Step 5: Build ANN model
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(8, activation='relu'))

In [ ]:
model.add(Dense(16, activation='relu'))

In [ ]:
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
# Step 6: Train model
model.fit(X_train,y_train,epochs=10,batch_size=32)

In [ ]:
model.summary()

In [ ]:
# Step 7: Prediction
y_pred = model.predict(X_test)

In [ ]:
y_pred = np.round(y_pred)

In [ ]:
# Step 8: Evaluate
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

# **Multi Classification**

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y_m,random_state=2529)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()

In [ ]:
X_train = mms.fit_transform(X_train)

In [ ]:
X_test = mms.transform(X_test)

In [ ]:
# Step 5: Build ANN model
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(8, activation='relu'))

In [ ]:
model.add(Dense(16, activation='relu'))

In [ ]:
model.add(Dense(3, activation='softmax'))

In [ ]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
# Step 6: Train model
model.fit(X_train,y_train,epochs=10,batch_size=32)

In [ ]:
model.summary()

In [ ]:
# Step 7: Prediction
y_pred = model.predict(X_test)

In [ ]:
y_pred = np.argmax(y_pred,axis=1)

In [ ]:
y_test = np.argmax(y_test,axis=1)

In [ ]:
# Step 8: Evaluate
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

# **Results**

The same dataset successfully solves three different machine learning problems.
| Problem                    | Output Layer | Loss Function            |
| -------------------------- | ------------ | ------------------------ |
| Regression                 | Linear       | Mean Squared Error       |
| Binary Classification      | Sigmoid      | Binary Crossentropy      |
| Multi-Class Classification | Softmax      | Categorical Crossentropy |

# **Learning Outcome**

This project demonstrates an important concept in Machine Learning.

The input features remain exactly the same.

Only the target variable changes.

Changing the target variable changes the learning task.
| Target Variable | Problem                    |
| --------------- | -------------------------- |
| Annual Return   | Regression                 |
| Return Binary   | Binary Classification      |
| Return Category | Multi-Class Classification |

# **Conclusion**

Artificial Neural Networks can effectively model investment portfolio performance for multiple business objectives using the same dataset. Depending on organizational requirements, the same feature set can be used for:

Predicting exact annual returns (Regression),Identifying whether returns are high or low (Binary Classification), or
Categorizing returns into multiple performance levels (Multi-class Classification).

This project highlights the flexibility of machine learning, where the business objective determines the prediction task rather than the input features.

# **Future Scope**
Hyperparameter tuning for improved performance
Experiment with deeper neural network architectures
Apply Dropout and Batch Normalization to reduce overfitting
Compare ANN with Random Forest, XGBoost, and Support Vector Machines
Deploy the trained model as a Streamlit web application for real-time investment return prediction